### ISSUE TITLE
tf: rotate secrets

### ISSUE THREAD

**Issue by wasaga** [pomerium/install#11]
## Is your feature request related to a problem? Please describe

currently, we generate secrets in Terraform using `random` provider. 
The secrets would be generated once unless they are manually removed. 

We should provide an easy way for the user to perform secret rotation. 

## Describe the solution you'd like

The `random` provider has [Resource Keepers](https://registry.terraform.io/providers/hashicorp/random/latest/docs#resource-keepers) which we can utilize for that purpose, by introducing i.e. `secrets_version` variable that can be just increased every time a user wishes to rotate the secrets, that would trigger secrets recreation.

**Comment by con-openai** [comment]
Something like this?
[pomerium.patch](https://github.com/user-attachments/files/17710824/pomerium.patch)
